### ISSUE TITLE
Upload to hackage

### ISSUE THREAD

**Issue by Anrock** [lpeterse/haskell-terminal#5]
@lpeterse could you upload this to hackage please?

**Comment by lpeterse** [comment]
Hi,

I uploaded it more or less as is to Hackage. It now builds with Stackage LTS 13.4.

There might be quirks in it which is why I hesitated publishing it yet, but it's probably to better to push it out now.

You might also want to have a look at [replique](https://github.com/lpeterse/haskell-replique) (though it's not yet finished).
